---

- conf-name: single-dut-mgmt43
  group-name: mgmt-only
  topo: m0
  vm_base: ""
  dut:
    - str-nexthop_4010-01
  inv_name: lab
  auto_recover: 'False'
  comment: Single DUT management-only testbed
