---
ansible_user: root
ansible_password: david
ansible_become_password: david

# Use the following username/password variables to login to vm hosts
# instead of the default variables (defined above).
vm_host_user: admin
vm_host_password: YourPaSsWoRd
vm_host_become_password: YourPaSsWoRd
